### ISSUE TITLE
Not working with Angular 5 : throws warning and if imported any module the app does not work

### ISSUE THREAD

**Issue by RakeshLchanSarma** [patternfly/patternfly-ng#192]
I was trying to implement Patternfly-ng 0.13.6 with angular 5.0.0 and angular-cli 1.5.0 versions, but I am getting the below warning: 

```
WARNING in ./node_modules/patternfly-ng/node_modules/@angular/core/@angular/core.es5.js
5675:15-102 Critical dependency: the request of a dependency is an expression
    at ImportLazyContextDependency.getWarnings (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\dependencies\ContextDependency.js:39:18)
    at Compilation.reportDependencyErrorsAndWarnings (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\Compilation.js:703:24)
    at Compilation.finish (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\Compilation.js:561:9)
    at applyPluginsParallel.err (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\Compiler.js:506:17)
    at F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\tapable\lib\Tapable.js:289:11
    at _addModuleChain (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\Compilation.js:507:11)
    at processModuleDependencies.err (F:\SematreeProjects\Ng2\st-resource-allocation-ui\node_modules\webpack\lib\Compilation.js:477:14)
    at _combinedTickCallback (internal/process/next_tick.js:73:7)
    at process._tickCallback (internal/process/next_tick.js:104:9)
 @ ./node_modules/patternfly-ng/node_modules/@angular/core/@angular/core.es5.js
 @ ./node_modules/patternfly-ng/src/app/wizard/wizard-substep.component.js
 @ ./node_modules/patternfly-ng/index.js
 @ ./src/app/app.module.ts
 @ ./src/main.ts
 @ multi webpack-dev-server/client?http://0.0.0.0:0 ./src/main.ts

```
app.module.ts:
```
import { NotificationModule } from 'patternfly-ng';
@NgModule({
  declarations: [
    ......
  ],
  imports: [
    .......
    NotificationModule
  ],
  providers: [....],
  bootstrap: [....]
})
export class AppModule { }
```
Please help me out fixing this issue.

**Comment by dlabrecq** [comment]
Angular 5 isn't currently supported, but we're working on it. 

For starters, we've fixed some deprecations that have been removed from 5 -- see https://github.com/patternfly/patternfly-ng/pull/199.

Note that patternfly-ng currently depends on libraries like ngx-bootstrap, angular-tree-component, etc. that may not yet support Angular 5.

In the mean time, you can try Angular 4 by installing `@angluar/cli@1.4.1`

**Comment by dlabrecq** [comment]
FYI, I modified our peerDependencies to work with both Angular 4 and 5. See: https://github.com/patternfly/patternfly-ng/pull/201

Unfortunately, angular-tree-component still uses deprecated ngOutletContext, which causes Angular 5 builds to fail. Once we have a fix for that, it should work fine.

**Comment by dlabrecq** [comment]
angular-tree-component 6.0.0 builds fine, so this should be all set after #201 is merged. Please reopen if you encounter further issues.

**Comment by helio-frota** [comment]
@dlabrecq thanks!
